# Generated by Django 5.1.3 on 2024-12-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('token', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('user', models.CharField(max_length=150)),
                ('created', models.PositiveBigIntegerField()),
            ],
            options={
                'db_table': 'sessions',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
    ]
